shadow = false  # Don't draw shadows around stacked views
borders = "simple"  # Alternatives are "none" and "outset"

[colors]
    background = "#000000"
    shadow     = "#000000"
    view       = "#222222"

    primary   = "#ccc9c9"
    secondary = "#111111"
    tertiary  = "#444444"

    title_primary   = "#ff5555"
    title_secondary = "#ffff55"

    highlight          = "#900"
    highlight_inactive = "#5555FF"

[styles]
    editable_text = { effects = [], front = "primary", back = "secondary" }
